### ISSUE TITLE
BoatRaceResources.sb2 missing the course backdrop

### ISSUE THREAD

**Issue by ninaszymor** [raspberrypilearning/boat-race#156]
I just noticed that the BoatRaceResources.sb2 is missing the course backdrop. Instead, it contains two costumes for the boat sprite - normal and crashed. Is this correct? I thought the sb2 file should be the same as the jumpto.cc/boat-go link. Am I mistaken or should the sb2 file in the resources folder be corrected?

**Comment by rik-cross** [comment]
fixed!
